<a href="https://colab.research.google.com/github/granantuin/LEVX_class/blob/master/Display_data_model_label_dir.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install pandas_ml

In [0]:
from sklearn.metrics import confusion_matrix ,accuracy_score,f1_score,recall_score
from sklearn.metrics import precision_recall_fscore_support
from pandas_ml import ConfusionMatrix
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [0]:
from google.colab import drive
drive.mount('/content/drive')

In [0]:
def evaluate():
  for label in x_data.columns:
    print(label)
    index=["E","N","NE","NW","S","SE","SW","W"]
    print(ConfusionMatrix(y_data["label"],x_data[label]))
    print("****************")
    print("****************")
    results= precision_recall_fscore_support(y_data["label"], x_data[label], average=None, )
    df=pd.DataFrame({"Precision":results[0],"Recall":results[1],"F1":results[2],"W_DIR":index})
    df=df.set_index("W_DIR")
    print(df)
    print("*******************************************************")
    print("Accuracy=","{:.2%}".format(accuracy_score(y_data["label"], x_data[label])))
    print("Average precision =","{:.2%}".format(df["Precision"].mean()))
    print("Average recall =","{:.2%}".format(df["Recall"].mean()))
    results= precision_recall_fscore_support(y_data["label"], x_data[label], average='weighted', )
    print("Precision weighted=","{:.2%}".format(results[0]))
    print("Recall weighted =","{:.2%}".format(results[1]))
    print("*******************************************************")

In [0]:
drive_4km="/content/drive/My Drive/Colab Notebooks/model_vs_data/Coron_4km_h24toh48_dir/"
drive_1km="/content/drive/My Drive/Colab Notebooks/model_vs_data/Coron_Mars_H24to48_dir/"
drive_metar="/content/drive/My Drive/Colab Notebooks/model_vs_data/Metar_2018/"
dr=[drive_4km,drive_1km,drive_metar]

In [0]:
y_data=pd.read_excel(dr[2]+"y_LEVX_dir.xlsx",index_col=0)
x_data=pd.read_csv(dr[2]+"x_LEVX.csv",index_col=0)
x_data=x_data.iloc[:,0:9]
y_data=y_data[y_data>0]# delete station errors
result = x_data.join(y_data, how='outer').dropna()
x_data=result.iloc[:,0:9]
y_data=result.iloc[:,9:10]

In [22]:
x_data.describe()

,0,1,2,3,4,5,6,7,8
count,6706.000000,6706.000000,6706.000000,6706.000000,6706.000000,6706.000000,6706.000000,6706.000000,6706.000000
mean,202.611930,208.045731,208.979718,185.839959,213.542731,210.897068,189.612311,209.744967,201.993788
std,104.719044,105.966631,108.106277,102.864678,99.110239,100.978526,100.609803,94.126899,99.209816
min,0.005546,0.059805,0.015955,0.004262,0.011393,0.243565,0.026720,0.042866,0.026938
25%,123.450954,122.639519,123.120085,107.338276,139.874969,126.467817,122.359901,140.456303,120.706581
50%,200.364281,209.059570,214.826431,182.692093,212.253288,209.316063,194.348999,210.316307,194.466972
75%,297.100792,300.518997,305.612801,275.406479,298.876770,305.079521,259.450729,288.404350,294.421410
max,359.986725,359.988281,359.983948,359.924500,359.925232,359.980194,359.997559,359.969696,359.947845

In [23]:
y_data.describe()

             value
count  6706.000000
mean    197.216224
std      96.559469
min      10.000000
25%     180.000000
50%     210.000000
75%     260.000000
max     360.000000

In [0]:
NE=y_data[(y_data["value"]>22.5) & (y_data["value"]<67.5)]
NE["label"]="NE"
E=y_data[(y_data["value"]>67.5) & (y_data["value"]<112.5)]
E["label"]="E"
SE=y_data[(y_data["value"]>112.5) & (y_data["value"]<157.5)]
SE["label"]="SE"
S=y_data[(y_data["value"]>157.5) & (y_data["value"]<202.5)]
S["label"]="S"
SW=y_data[(y_data["value"]>202.5) & (y_data["value"]<247.5)]
SW["label"]="SW"
W=y_data[(y_data["value"]>247.5) & (y_data["value"]<292.5)]
W["label"]="W"
NW=y_data[(y_data["value"]>292.5) & (y_data["value"]<337.5)]
NW["label"]="NW"
N=y_data[(y_data["value"]>337.5) | (y_data["value"]<22.5)]
N["label"]="N"
winds=[NE,N,E,SE,S,SW,W,NW]
y_data=pd.concat(winds)
y_data=y_data.sort_index()

In [25]:
y_data

                     value label
2018-01-02 00:00:00  210.0    SW
2018-01-02 01:00:00  220.0    SW
2018-01-02 03:00:00  180.0     S
2018-01-02 04:00:00  200.0     S
2018-01-02 05:00:00  210.0    SW
2018-01-02 06:00:00  210.0    SW
2018-01-02 07:00:00  180.0     S
2018-01-02 09:00:00  210.0    SW
2018-01-02 10:00:00  230.0    SW
2018-01-02 11:00:00  240.0    SW
2018-01-02 12:00:00  240.0    SW
2018-01-02 13:00:00  240.0    SW
2018-01-02 14:00:00  240.0    SW
2018-01-02 15:00:00  240.0    SW
2018-01-02 16:00:00  250.0     W
2018-01-02 17:00:00  230.0    SW
2018-01-02 18:00:00  240.0    SW
2018-01-02 19:00:00  240.0    SW
2018-01-02 20:00:00  230.0    SW
2018-01-02 21:00:00  220.0    SW
2018-01-02 22:00:00  230.0    SW
2018-01-02 23:00:00  240.0    SW
2018-01-03 00:00:00  240.0    SW
2018-01-03 01:00:00  240.0    SW
2018-01-03 03:00:00  230.0    SW
2018-01-03 04:00:00  240.0    SW
2018-01-03 05:00:00  230.0    SW
2018-01-03 06:00:00  240.0    SW
2018-01-03 07:00:00  240.0    SW
2018-01-03 08:00:00  240.0    SW
...                    ...   ...
2018-12-29 17:00:00  200.0     S
2018-12-29 18:00:00  210.0    SW
2018-12-29 19:00:00  220.0    SW
2018-12-29 20:00:00  200.0     S
2018-12-29 21:00:00  230.0    SW
2018-12-29 22:00:00  240.0    SW
2018-12-29 23:00:00  240.0    SW
2018-12-30 00:00:00  220.0    SW
2018-12-30 01:00:00  230.0    SW
2018-12-30 02:00:00  230.0    SW
2018-12-30 03:00:00  220.0    SW
2018-12-30 04:00:00  210.0    SW
2018-12-30 05:00:00  220.0    SW
2018-12-30 06:00:00  250.0     W
2018-12-30 07:00:00  230.0    SW
2018-12-30 08:00:00  220.0    SW
2018-12-30 09:00:00  210.0    SW
2018-12-30 10:00:00  210.0    SW
2018-12-30 11:00:00  200.0     S
2018-12-30 12:00:00  200.0     S
2018-12-30 13:00:00  200.0     S
2018-12-30 14:00:00  200.0     S
2018-12-30 16:00:00  210.0    SW
2018-12-30 17:00:00  230.0    SW
2018-12-30 18:00:00  240.0    SW
2018-12-30 19:00:00  240.0    SW
2018-12-30 20:00:00  220.0    SW
2018-12-30 21:00:00  230.0    SW
2018-12-30 22:00:00  250.0     W
2018-12-30 23:00:00  230.0    SW

[6706 rows x 2 columns]

In [0]:
for c in ['0', '1', '2', '3', '4', '5', '6', '7', '8']:
  NE=x_data[(x_data[c]>22.5) & (x_data[c]<67.5)]
  NE["label"+c]="NE"
  E=x_data[(x_data[c]>67.5) & (x_data[c]<112.5)]
  E["label"+c]="E"
  SE=x_data[(x_data[c]>112.5) & (x_data[c]<157.5)]
  SE["label"+c]="SE"
  S=x_data[(x_data[c]>157.5) & (x_data[c]<202.5)]
  S["label"+c]="S"
  SW=x_data[(x_data[c]>202.5) & (x_data[c]<247.5)]
  SW["label"+c]="SW"
  W=x_data[(x_data[c]>247.5) & (x_data[c]<292.5)]
  W["label"+c]="W"
  NW=x_data[(x_data[c]>292.5) & (x_data[c]<337.5)]
  NW["label"+c]="NW"
  N=x_data[(x_data[c]>337.5) | (x_data[c]<22.5)]
  N["label"+c]="N"
  winds=[NE,N,E,SE,S,SW,W,NW]
  x_data=pd.concat(winds)
  x_data=x_data.sort_index()

In [27]:
x_data

,0,1,2,3,4,5,6,7,8,label0,label1,label2,label3,label4,label5,label6,label7,label8
2018-01-02 00:00:00,227.609344,228.460449,226.499741,225.213150,229.416656,229.683624,219.294083,225.839172,229.653519,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 01:00:00,228.952545,228.338745,226.010056,228.746536,230.614944,228.558990,222.122345,227.556030,229.009384,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 03:00:00,225.514114,221.407166,209.874344,223.545639,222.975174,215.568253,218.710022,219.703888,217.077179,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 04:00:00,217.037811,215.657928,210.978577,216.013275,217.305695,214.257828,213.779495,214.309631,212.561752,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 05:00:00,217.165268,218.630081,217.867554,215.320389,219.081924,219.730835,211.384262,216.835297,218.448975,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 06:00:00,221.662170,221.538254,218.864426,220.317123,222.784607,220.536713,213.339249,217.716599,218.254745,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 07:00:00,231.308334,227.990128,223.421463,229.943909,232.012238,227.375427,223.334793,229.147263,229.410828,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 09:00:00,240.922058,237.748474,231.875549,239.659027,241.528870,236.223175,233.453735,240.165421,241.252518,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 10:00:00,244.410934,242.244095,239.383484,243.327545,245.722290,241.603119,236.739532,244.005814,245.658813,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 11:00:00,247.084213,244.742279,241.644287,243.848877,245.583023,241.536865,238.062683,243.950256,244.456985,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 12:00:00,253.339630,253.190430,254.300446,249.748703,254.232040,254.359787,241.836533,249.270325,253.063980,W,W,W,W,W,W,SW,W,W
2018-01-02 13:00:00,255.952209,257.772766,257.999481,249.443588,252.974457,252.994141,240.581635,247.285278,251.166275,W,W,W,W,W,W,SW,SW,W
2018-01-02 14:00:00,247.606293,249.648102,252.337936,242.515762,246.251251,248.970551,235.098679,242.362289,246.964096,W,W,W,SW,SW,W,SW,SW,SW
2018-01-02 15:00:00,247.860291,248.106857,250.070816,246.570267,249.503281,249.718689,239.055054,245.001053,248.014969,W,W,W,SW,W,W,SW,SW,W
2018-01-02 16:00:00,244.767136,245.635773,244.581268,237.267166,242.755844,242.466660,227.335785,236.109436,240.421890,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 17:00:00,243.710709,244.320587,242.549576,239.086258,243.749481,241.892014,227.001633,236.616577,239.784058,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 18:00:00,241.737793,240.531525,236.871552,235.792938,239.353149,239.647629,226.270142,233.933655,238.907150,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 19:00:00,236.237946,232.454498,226.622177,234.594421,234.824142,231.295883,226.920944,233.822113,234.395050,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 20:00:00,234.284439,228.015778,217.359985,229.764374,227.051376,224.195175,223.794174,226.055984,228.942535,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 21:00:00,232.040131,224.248627,210.805267,229.344513,227.113708,215.962036,223.891632,226.646072,220.099579,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 22:00:00,239.532166,232.987793,221.342712,238.879242,238.240326,229.976959,228.193420,234.399994,234.279739,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 23:00:00,231.675751,220.170685,208.162704,227.232178,222.014725,209.178238,219.959335,218.923187,206.574295,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 00:00:00,226.697678,230.663101,231.147583,223.984604,229.798538,231.371674,218.034378,225.435303,229.479080,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 01:00:00,224.838181,221.735046,220.476273,225.787903,225.990875,222.887878,219.218246,224.675232,225.485962,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 03:00:00,232.584717,229.561264,226.046387,232.725769,234.665878,230.517090,224.277466,234.182297,236.929245,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 04:00:00,239.468201,236.321030,234.101608,238.228867,240.035690,237.477341,228.518936,237.080124,240.860855,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 05:00:00,239.040421,236.951752,234.808792,237.632431,240.641434,237.314163,227.695465,236.941483,241.032349,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 06:00:00,241.043900,241.345718,240.468460,235.829422,239.208084,237.509995,226.318253,234.757095,237.903488,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 07:00:00,242.900726,242.759827,239.590332,239.325592,241.217636,238.205811,229.934311,237.575287,239.197510,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 08:00:00,235.602097,236.675613,231.307785,231.748596,233.108368,231.925217,224.971298,230.954636,232.781693,SW,SW,SW,SW,SW,SW,SW,SW,SW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-29 17:00:00,32.774006,23.518007,2.181672,67.499207,25.575016,339.856689,103.920860,74.067581,331.314606,NE,NE,N,NE,NE,N,E,E,NW
2018-12-29 18:00:00,127.300980,151.868790,242.959702,106.359077,110.086334,215.236755,104.164566,132.327118,132.994308,SE,SE,SW,E,E,SW,E,SE,SE
2018-12-29 19:00:00,142.748077,289.130646,298.704712,121.903053,145.875488,311.556641,121.517883,159.401932,130.599030,SE,W,NW,SE,SE,NW,SE,S,SE
2018-12-29 20:00:00,145.904724,165.647461,231.191299,119.485825,124.670868,123.045280,126.602829,167.175903,134.151657,SE,S,SW,SE,SE,SE,SE,S,SE
2018-12-29 21:00:00,154.867737,198.833588,270.393768,140.533676,147.537140,140.801483,148.150223,148.851273,115.416451,SE,S,W,SE,SE,SE,SE,SE,SE
2018-12-29 22:00:00,127.777130,70.124023,51.606995,115.552071,104.613716,80.228134,114.369194,112.337402,90.851349,SE,E,NE,SE,E,E,SE,E,E
2018-12-29 23:00:00,94.246498,69.337402,55.968811,93.883896,85.680710,69.893021,88.490158,95.023636,83.128372,E,E,NE,E,E,E,E,E,E
2018-12-30 00:00:00,65.846161,45.329014,4.423804,84.540749,90.597946,64.522530,66.320015,186.215744,168.471985,NE,NE,N,E,E,NE,NE,S,S
2018-12-30 01:00:00,70.061127,53.110321,15.511469,87.676399,91.955788,75.026917,67.786156,178.413315,126.413719,E,NE,N,E,E,E,E,S,SE
2018-12-30 02:00:00,78.205940,64.600586,21.279509,104.452957,104.867691,97.122307,116.051384,124.858780,110.326538,E,NE,N,E,E,E,SE,SE,E
2018-12-30 03:00:00,78.767601,50.011517,359.377319,109.415009,112.460510,120.060051,120.489479,133.795135,122.357674,E,NE,N,E,E,SE,SE,SE,SE
2018-12-30 04:00:00,74.707809,46.210056,5.109692,104.371765,103.533943,98.566429,116.240280,129.019775,120.702797,E,NE,N,E,E,E,SE,SE,SE
2018-12-30 05:00:00,74.164406,52.878613,21.476082,100.996071,98.076324,88.501793,114.909592,122.730003,112.007156,E,NE,N,E,E,E,SE,SE,E
2018-12-30 06:00:00,71.143524,52.413834,21.397398,96.976311,93.790871,82.484177,112.434608,119.178741,109.129021,E,NE,N,E,E,E,E,SE,E
2018-12-30 07:00:00,71.468285,50.809719,14.435632,97.000626,91.712090,75.792229,106.732277,113.475044,107.507858,E,NE,N,E,E,E,E,SE,E
2018-12-30 08:00:00,75.478203,52.322445,9.469948,103.487663,96.548134,79.564354,111.048737,119.234581,113.311226,E,NE,N,E,E,E,E,SE,SE
2018-12-30 09:00:00,83.208229,49.998760,2.562523,117.123016,110.291245,105.671516,128.291473,130.954865,123.384331,E,NE,N,SE,E,E,SE,SE,SE
2018-12-30 10:00:00,33.724140,6.026276,351.372192,150.749847,135.502670,140.975677,159.316208,148.980438,136.916565,NE,N,N,SE,SE,SE,S,SE,SE
2018-12-30 11:00:00,315.594421,333.047394,343.715790,258.041077,210.018951,117.952797,232.562225,187.103409,143.605957,NW,NW,N,W,SW,SE,SW,S,SE
2018-12-30 12:00:00,302.405060,310.996399,324.586121,289.843262,296.591431,346.072235,249.716690,232.663940,151.935394,NW,NW,NW,W,NW,N,W,SW,SE
2018-12-30 13:00:00,306.425171,307.910797,306.148834,299.857269,302.168243,308.285309,252.283310,268.633209,226.572830,NW,NW,NW,NW,NW,NW,W,W,SW
2018-12-30 14:00:00,313.923004,315.081726,313.773895,302.851959,306.929199,314.807678,264.694977,283.147064,315.853485,NW,NW,NW,NW,NW,NW,W,W,NW
2018-12-30 16:00:00,316.486145,328.200684,340.081879,291.311157,336.608215,354.388031,234.043198,293.982147,353.588257,NW,NW,N,W,NW,N,SW,NW,N
2018-12-30 17:00:00,338.662140,12.562276,37.403534,24.524286,28.754658,42.976696,200.479614,21.584900,15.459204,N,N,NE,NE,NE,NE,S,N,N
2018-12-30 18:00:00,37.899872,55.081184,39.973900,58.996632,57.586906,42.011181,95.338432,69.278061,43.510216,NE,NE,NE,NE,NE,NE,E,E,NE
2018-12-30 19:00:00,66.216301,66.998878,40.247601,69.533813,82.019638,66.909218,81.011536,98.566925,104.362366,NE,NE,NE,E,E,NE,E,E,E
2018-12-30 20:00:00,109.541565,101.889999,72.441177,103.448425,111.796669,106.482788,101.278336,127.757782,128.617737,E,E,E,E,E,E,E,SE,SE
2018-12-30 21:00:00,156.302185,125.060509,75.442741,124.197609,119.422661,109.052681,135.748550,134.931778,129.159180,SE,SE,E,SE,SE,E,SE,SE,SE
2018-12-30 22:00:00,129.416748,46.474384,30.194983,116.383720,113.441383,85.068016,121.605263,120.714058,109.244637,SE,NE,NE,SE,SE,E,SE,SE,E
2018-12-30 23:00:00,77.036827,49.072395,33.923553,110.648598,94.619835,73.167557,114.341980,113.155937,99.704117,E,NE,NE,E,E,E,SE,SE,E

In [0]:
x_data=x_data.iloc[:, 9:]

In [29]:
x_data

,label0,label1,label2,label3,label4,label5,label6,label7,label8
2018-01-02 00:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 01:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 03:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 04:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 05:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 06:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 07:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 09:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 10:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 11:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 12:00:00,W,W,W,W,W,W,SW,W,W
2018-01-02 13:00:00,W,W,W,W,W,W,SW,SW,W
2018-01-02 14:00:00,W,W,W,SW,SW,W,SW,SW,SW
2018-01-02 15:00:00,W,W,W,SW,W,W,SW,SW,W
2018-01-02 16:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 17:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 18:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 19:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 20:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 21:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 22:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-02 23:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 00:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 01:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 03:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 04:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 05:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 06:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 07:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
2018-01-03 08:00:00,SW,SW,SW,SW,SW,SW,SW,SW,SW
...,...,...,...,...,...,...,...,...,...
2018-12-29 17:00:00,NE,NE,N,NE,NE,N,E,E,NW
2018-12-29 18:00:00,SE,SE,SW,E,E,SW,E,SE,SE
2018-12-29 19:00:00,SE,W,NW,SE,SE,NW,SE,S,SE
2018-12-29 20:00:00,SE,S,SW,SE,SE,SE,SE,S,SE
2018-12-29 21:00:00,SE,S,W,SE,SE,SE,SE,SE,SE
2018-12-29 22:00:00,SE,E,NE,SE,E,E,SE,E,E
2018-12-29 23:00:00,E,E,NE,E,E,E,E,E,E
2018-12-30 00:00:00,NE,NE,N,E,E,NE,NE,S,S
2018-12-30 01:00:00,E,NE,N,E,E,E,E,S,SE
2018-12-30 02:00:00,E,NE,N,E,E,E,SE,SE,E
2018-12-30 03:00:00,E,NE,N,E,E,SE,SE,SE,SE
2018-12-30 04:00:00,E,NE,N,E,E,E,SE,SE,SE
2018-12-30 05:00:00,E,NE,N,E,E,E,SE,SE,E
2018-12-30 06:00:00,E,NE,N,E,E,E,E,SE,E
2018-12-30 07:00:00,E,NE,N,E,E,E,E,SE,E
2018-12-30 08:00:00,E,NE,N,E,E,E,E,SE,SE
2018-12-30 09:00:00,E,NE,N,SE,E,E,SE,SE,SE
2018-12-30 10:00:00,NE,N,N,SE,SE,SE,S,SE,SE
2018-12-30 11:00:00,NW,NW,N,W,SW,SE,SW,S,SE
2018-12-30 12:00:00,NW,NW,NW,W,NW,N,W,SW,SE
2018-12-30 13:00:00,NW,NW,NW,NW,NW,NW,W,W,SW
2018-12-30 14:00:00,NW,NW,NW,NW,NW,NW,W,W,NW
2018-12-30 16:00:00,NW,NW,N,W,NW,N,SW,NW,N
2018-12-30 17:00:00,N,N,NE,NE,NE,NE,S,N,N
2018-12-30 18:00:00,NE,NE,NE,NE,NE,NE,E,E,NE
2018-12-30 19:00:00,NE,NE,NE,E,E,NE,E,E,E
2018-12-30 20:00:00,E,E,E,E,E,E,E,SE,SE
2018-12-30 21:00:00,SE,SE,E,SE,SE,E,SE,SE,SE
2018-12-30 22:00:00,SE,NE,NE,SE,SE,E,SE,SE,E
2018-12-30 23:00:00,E,NE,NE,E,E,E,SE,SE,E

In [30]:
evaluate()

label0
Predicted    E     N   NE    NW     S   SE   SW    W  __all__
Actual
E           49    11   21    32     6   11    1    7      138
N           69   613   89   249     7   18    6   33     1084
NE          69   327   90   135     6   12    6   25      670
NW           8    40    9   176     2    6    4   46      291
S          151    19   17    56   826  358  194  126     1747
SE          14     4    1     7     1    7    3    1       38
SW         337    34   33    74   204  293  268  162     1405
W           71    47   14   657    42   38   54  410     1333
__all__    768  1095  274  1386  1094  743  536  810     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.063802  0.355072  0.108168
N       0.559817  0.565498  0.562643
NE      0.328467  0.134328  0.190678
NW      0.126984  0.604811  0.209899
S       0.755027  0.472811  0.581485
SE      0.009421  0.184211  0.017926
SW      0.500000  0.190747  0.276146
W       0.506173  0.307577  0.382641
*******************************************************
Accuracy= 36.37%
Average precision = 35.62%
Average recall = 35.19%
Precision weighted= 53.23%
Recall weighted = 36.37%
*******************************************************
label1
Predicted    E     N   NE    NW     S   SE   SW    W  __all__
Actual
E           52    14   22    26     8    4    7    5      138
N           65   607  115   245     6    9    8   29     1084
NE          68   328   81   135     7    6   15   30      670
NW          11    50   13   162     5    1    4   45      291
S          149    18   70    51   821  316  216  106     1747
SE          13     2    5     6     3    4    0    5       38
SW         246    43  224    65   200  177  300  150     1405
W           43    54   58   663    41   19   81  374     1333
__all__    647  1116  588  1353  1091  536  631  744     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.080371  0.376812  0.132484
N       0.543907  0.559963  0.551818
NE      0.137755  0.120896  0.128776
NW      0.119734  0.556701  0.197080
S       0.752521  0.469948  0.578576
SE      0.007463  0.105263  0.013937
SW      0.475436  0.213523  0.294695
W       0.502688  0.280570  0.360135
*******************************************************
Accuracy= 35.80%
Average precision = 32.75%
Average recall = 33.55%
Precision weighted= 50.42%
Recall weighted = 35.80%
*******************************************************
label2
Predicted    E     N   NE    NW     S   SE   SW    W  __all__
Actual
E           35     9   48    16     9    3    9    9      138
N           41   492  132   350     8   12   11   38     1084
NE          46   254  114   186    10    7   21   32      670
NW          11    55    8   153     8    4    7   45      291
S          149    41  127    47   746  286  267   84     1747
SE           9     5    8     3     4    4    3    2       38
SW         140   103  326    95   178   98  336  129     1405
W           29    67   74   607    40   15  109  392     1333
__all__    460  1026  837  1457  1003  429  763  731     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.076087  0.253623  0.117057
N       0.479532  0.453875  0.466351
NE      0.136201  0.170149  0.151294
NW      0.105010  0.525773  0.175057
S       0.743769  0.427018  0.542545
SE      0.009324  0.105263  0.017131
SW      0.440367  0.239146  0.309963
W       0.536252  0.294074  0.379845
*******************************************************
Accuracy= 33.88%
Average precision = 31.58%
Average recall = 30.86%
Precision weighted= 48.99%
Recall weighted = 33.88%
*******************************************************
label3
Predicted    E     N   NE   NW     S   SE   SW     W  __all__
Actual
E           48    20   16   21     4   10    1    18      138
N           67   613  142  142     9   31   10    70     1084
NE          47   336  128   70     5    9    7    68      670
NW          11    43   21  127     3    8    7    71      291
S          142    14   21   47   844  319  236   124     1747
SE          13     4    4    4     1    6    1     5       38
SW         286    27   24   31   211  354  289   183     1405
W           61    70   25  199    49   49   64   816     1333
__all__    675  1127  381  641  1126  786  615  1355     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.071111  0.347826  0.118081
N       0.543922  0.565498  0.554500
NE      0.335958  0.191045  0.243578
NW      0.198128  0.436426  0.272532
S       0.749556  0.483114  0.587539
SE      0.007634  0.157895  0.014563
SW      0.469919  0.205694  0.286139
W       0.602214  0.612153  0.607143
*******************************************************
Accuracy= 42.81%
Average precision = 37.23%
Average recall = 37.50%
Precision weighted= 54.50%
Recall weighted = 42.81%
*******************************************************
label4
Predicted    E     N   NE    NW     S   SE   SW     W  __all__
Actual
E           60    15    7    33     6    9    4     4      138
N           82   591   66   236     9   34   10    56     1084
NE          67   313   68   158    10   17    9    28      670
NW          11    52    4   156     4    9    3    52      291
S          167    18   10    48   827  361  206   110     1747
SE          14     3    0     8     2    9    1     1       38
SW         348    21   30    59   228  274  280   165     1405
W           73    59   13   416    52   42   64   614     1333
__all__    822  1072  198  1114  1138  755  577  1030     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.072993  0.434783  0.125000
N       0.551306  0.545203  0.548237
NE      0.343434  0.101493  0.156682
NW      0.140036  0.536082  0.222064
S       0.726714  0.473383  0.573310
SE      0.011921  0.236842  0.022699
SW      0.485269  0.199288  0.282543
W       0.596117  0.460615  0.519678
*******************************************************
Accuracy= 38.85%
Average precision = 36.60%
Average recall = 37.35%
Precision weighted= 54.06%
Recall weighted = 38.85%
*******************************************************
label5
Predicted    E    N   NE    NW     S   SE   SW    W  __all__
Actual
E           67    9   10    25     8    9    3    7      138
N           85  399   86   438     8   22    9   37     1084
NE          85  197   66   257    10   13   12   30      670
NW          12   44    6   168     6    8    7   40      291
S          222   12   27    53   772  380  203   78     1747
SE          18    1    1     8     2    6    0    2       38
SW         368   41  107    75   213  182  287  132     1405
W           81   48   35   627    50   24   88  380     1333
__all__    938  751  338  1651  1069  644  609  706     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.071429  0.485507  0.124535
N       0.531292  0.368081  0.434877
NE      0.195266  0.098507  0.130952
NW      0.101757  0.577320  0.173018
S       0.722170  0.441900  0.548295
SE      0.009317  0.157895  0.017595
SW      0.471264  0.204270  0.285005
W       0.538244  0.285071  0.372732
*******************************************************
Accuracy= 31.99%
Average precision = 33.01%
Average recall = 32.73%
Precision weighted= 50.52%
Recall weighted = 31.99%
*******************************************************
label6
Predicted    E     N   NE   NW     S   SE    SW    W  __all__
Actual
E           32    29   18   21     1   10     6   21      138
N           52   684   73  113    24   42    46   50     1084
NE          31   398   86   62     6    8    26   53      670
NW          16    54   13  102     7    9    26   64      291
S          111    26   18   47   895  251   285  114     1747
SE           8     3    5    5     2    8     1    6       38
SW         180    32   25   24   235  414   361  134     1405
W           44    81   14  155    62   62   415  500     1333
__all__    474  1307  252  529  1232  804  1166  942     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.067511  0.231884  0.104575
N       0.523336  0.630996  0.572146
NE      0.341270  0.128358  0.186551
NW      0.192817  0.350515  0.248780
S       0.726461  0.512307  0.600873
SE      0.009950  0.210526  0.019002
SW      0.309605  0.256940  0.280825
W       0.530786  0.375094  0.439560
*******************************************************
Accuracy= 39.79%
Average precision = 33.77%
Average recall = 33.71%
Precision weighted= 48.81%
Recall weighted = 39.79%
*******************************************************
label7
Predicted    E    N   NE   NW     S    SE   SW     W  __all__
Actual
E           48   14    8   33     4    11    4    16      138
N           61  501   69  260    29    69   28    67     1084
NE          47  275   76  158    11    24   15    64      670
NW          11   36   13  131     7    11    5    77      291
S          133   13   12   52   749   464  211   113     1747
SE          11    1    2    9     1    11    0     3       38
SW         265   18   13   48   204   411  289   157     1405
W           60   43   19  256    42    68   88   757     1333
__all__    636  901  212  947  1047  1069  640  1254     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.075472  0.347826  0.124031
N       0.556049  0.462177  0.504786
NE      0.358491  0.113433  0.172336
NW      0.138332  0.450172  0.211632
S       0.715377  0.428735  0.536149
SE      0.010290  0.289474  0.019874
SW      0.451562  0.205694  0.282641
W       0.603668  0.567892  0.585234
*******************************************************
Accuracy= 38.20%
Average precision = 36.37%
Average recall = 35.82%
Precision weighted= 53.43%
Recall weighted = 38.20%
*******************************************************
label8
Predicted    E    N   NE    NW    S    SE   SW    W  __all__
Actual
E           64    9    9    30    6     3    6   11      138
N          116  382  141   327   17    31   11   59     1084
NE          80  174  112   211   11    13   17   52      670
NW          17   41   10   156    6    10    3   48      291
S          164   12   18    54  655   584  157  103     1747
SE          15    1    0     9    1    10    0    2       38
SW         367   25   35    61  185   332  246  154     1405
W           94   54   19   473   37    62   62  532     1333
__all__    917  698  344  1321  918  1045  502  961     6706
****************
****************
       Precision    Recall        F1
W_DIR
E       0.069793  0.463768  0.121327
N       0.547278  0.352399  0.428732
NE      0.325581  0.167164  0.220907
NW      0.118092  0.536082  0.193548
S       0.713508  0.374928  0.491557
SE      0.009569  0.263158  0.018467
SW      0.490040  0.175089  0.257997
W       0.553590  0.399100  0.463819
*******************************************************
Accuracy= 32.17%
Average precision = 35.34%
Average recall = 34.15%
Precision weighted= 52.62%
Recall weighted = 32.17%
*******************************************************